import React, {createContext, useContext, useMemo} from 'react';
import ReactMarkdown, {
	type Components,
	defaultUrlTransform,
} from 'react-markdown';
import remarkBreaks from 'remark-breaks';
import remarkGfm from 'remark-gfm';
import {CONTENT_FONT, GUI_THEME, TEXT} from '../lib/gui-theme';
import {
	remarkTicketRefs,
	TICKET_REF_URL_PREFIX,
} from '../lib/remark-ticket-refs';

// react-markdown wraps a fenced block in <pre><code>, and only sets a
// className on the <code> when the fence names a language — so keying
// block-vs-inline off className alone renders a bare ``` fence as inline,
// wrapping it into one ragged background box per line. Being inside a <pre>
// is the thing that actually distinguishes the two.
const InPre = createContext(false);

// Supplied by whoever knows the board, and read straight by MarkdownContent
// rather than threaded through every component that renders prose — a comment
// body sits four levels below the only place that can resolve a ref.
export type TicketRefLinks = {
	// Both halves are needed: a ref's shape alone can't be told apart from an
	// ordinary uppercase word, so only refs that resolve to a real ticket
	// become links.
	isKnownRef: (ref: string) => boolean;
	onOpen: (ref: string) => void;
};

const TicketRefLinksContext = createContext<TicketRefLinks | null>(null);

export const TicketRefLinksProvider = TicketRefLinksContext.Provider;

// react-markdown strips hrefs whose protocol isn't on its safe list, which
// would drop the ref marker before the anchor renderer ever sees it — the
// link then rendered as an ordinary anchor and opened a blank tab. The marker
// is generated by this app, not by the comment's author, so it is safe to let
// through; everything else still goes through the default sanitizer.
const urlTransform = (url: string): string =>
	url.startsWith(TICKET_REF_URL_PREFIX) ? url : defaultUrlTransform(url);

const CODE_FONT =
	'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace';

// Built per-instance rather than at module scope: the anchor renderer has to
// close over the ref-click handler.
const buildComponents = (
	onOpenTicketRef?: (ref: string) => void,
): Components => ({
	p: ({children}) => <p style={{margin: '0 0 14px'}}>{children}</p>,
	ul: ({children}) => (
		<ul style={{margin: '0 0 14px', paddingLeft: 20}}>{children}</ul>
	),
	ol: ({children}) => (
		<ol style={{margin: '0 0 14px', paddingLeft: 20}}>{children}</ol>
	),
	li: ({children}) => <li style={{margin: '2px 0'}}>{children}</li>,
	h1: ({children}) => (
		<h1 style={{fontSize: TEXT.prose + 2, margin: '0 0 14px'}}>{children}</h1>
	),
	h2: ({children}) => (
		<h2 style={{fontSize: TEXT.prose + 1, margin: '0 0 14px'}}>{children}</h2>
	),
	h3: ({children}) => (
		<h3 style={{fontSize: TEXT.prose, margin: '0 0 14px'}}>{children}</h3>
	),
	a: ({children, href}) => {
		// A ticket ref opens a ticket in this app, not a URL in a new tab, so it
		// is a control rather than an anchor — no href to leak into the address
		// bar or the middle-click menu.
		if (href?.startsWith(TICKET_REF_URL_PREFIX)) {
			const ref = href.slice(TICKET_REF_URL_PREFIX.length);

			return (
				<button
					type="button"
					title={`Open ${ref}`}
					onClick={() => onOpenTicketRef?.(ref)}
					style={{
						padding: 0,
						background: 'transparent',
						border: 'none',
						cursor: 'pointer',
						font: 'inherit',
						color: GUI_THEME.accent,
						textDecoration: 'underline',
						textUnderlineOffset: 2,
					}}
				>
					{children}
				</button>
			);
		}

		return (
			<a
				href={href}
				target="_blank"
				rel="noreferrer"
				style={{color: GUI_THEME.accent}}
			>
				{children}
			</a>
		);
	},
	// An attached image referenced from a body. Bounded to the column it sits
	// in — a screenshot is wider than any panel here — and clickable through to
	// the blob itself, which is the only way to read one at full size.
	img: ({src, alt}) => (
		<a
			href={typeof src === 'string' ? src : undefined}
			target="_blank"
			rel="noreferrer"
			style={{display: 'block'}}
		>
			<img
				src={typeof src === 'string' ? src : undefined}
				alt={alt ?? ''}
				loading="lazy"
				style={{
					display: 'block',
					maxWidth: '100%',
					borderRadius: 6,
					border: `1px solid ${GUI_THEME.line}`,
					cursor: 'zoom-in',
				}}
			/>
		</a>
	),
	blockquote: ({children}) => (
		<blockquote
			style={{
				margin: '0 0 14px',
				paddingLeft: 12,
				borderLeft: `2px solid ${GUI_THEME.line}`,
				color: GUI_THEME.secondary,
			}}
		>
			{children}
		</blockquote>
	),
	code: ({children}) => {
		const isBlock = useContext(InPre);

		// A block's own chrome (background, padding, scrolling) belongs to the
		// <pre> below, so that one contiguous box wraps every line rather than
		// each line carrying its own.
		return (
			<code
				style={
					isBlock
						? {fontFamily: CODE_FONT, fontSize: TEXT.ui}
						: {
								fontFamily: CODE_FONT,
								fontSize: '0.9em',
								background: GUI_THEME.bg,
								borderRadius: 4,
								padding: '1px 5px',
						  }
				}
			>
				{children}
			</code>
		);
	},
	pre: ({children}) => (
		<InPre.Provider value={true}>
			<pre
				style={{
					margin: '0 0 14px',
					padding: '10px 12px',
					background: GUI_THEME.bg,
					borderRadius: 6,
					overflowX: 'auto',
					whiteSpace: 'pre',
				}}
			>
				{children}
			</pre>
		</InPre.Provider>
	),
	hr: () => (
		<hr
			style={{
				border: 'none',
				borderTop: `1px solid ${GUI_THEME.line}`,
				margin: '12px 0',
			}}
		/>
	),
});

export const MarkdownContent = ({
	content,
	softBreaks = false,
}: {
	content: string;
	// Treats single newlines as line breaks (like a chat message) instead of
	// requiring a blank line for a new paragraph, per strict CommonMark.
	softBreaks?: boolean;
}) => {
	const ticketRefLinks = useContext(TicketRefLinksContext);

	const components = useMemo(
		() => buildComponents(ticketRefLinks?.onOpen),
		[ticketRefLinks],
	);

	const remarkPlugins = useMemo(
		() => [
			remarkGfm,
			...(softBreaks ? [remarkBreaks] : []),
			...(ticketRefLinks ? [remarkTicketRefs(ticketRefLinks.isKnownRef)] : []),
		],
		[softBreaks, ticketRefLinks],
	);

	return (
		<div
			style={{
				fontFamily: CONTENT_FONT,
				fontSize: TEXT.prose,
				lineHeight: 1.6,
				color: GUI_THEME.primary,
				wordBreak: 'break-word',
				// Cancels the last block child's trailing bottom margin via
				// collapsing, so the container doesn't end in dead whitespace.
				marginBottom: -14,
			}}
		>
			<ReactMarkdown
				remarkPlugins={remarkPlugins}
				components={components}
				urlTransform={urlTransform}
			>
				{content}
			</ReactMarkdown>
		</div>
	);
};
