import {colors} from '../theme/themes.js';

export type TagColor = string;

const TAG_COLORS = {
	red: colors.red,
	yellow: colors.yellow,
	green: colors.green,
	blue: colors.blue,
	magenta: colors.magenta,
	cyan: colors.cyan,
} as const;

export type TagsDefault = Record<string, TagColor>;

export const TAGS_DEFAULT: TagsDefault = {
	// RED — urgent / failures
	urgent: TAG_COLORS.red,
	critical: TAG_COLORS.red,
	important: TAG_COLORS.red,
	blocker: TAG_COLORS.red,
	asap: TAG_COLORS.red,
	immediate: TAG_COLORS.red,
	fail: TAG_COLORS.red,
	failure: TAG_COLORS.red,
	broken: TAG_COLORS.red,
	bug: TAG_COLORS.red,
	error: TAG_COLORS.red,
	incident: TAG_COLORS.red,
	outage: TAG_COLORS.red,
	production: TAG_COLORS.red,
	crash: TAG_COLORS.red,
	security: TAG_COLORS.red,

	// YELLOW — warnings / review
	warning: TAG_COLORS.yellow,
	warn: TAG_COLORS.yellow,
	risky: TAG_COLORS.yellow,
	risk: TAG_COLORS.yellow,
	attention: TAG_COLORS.yellow,
	pending: TAG_COLORS.yellow,
	review: TAG_COLORS.yellow,
	'needs-review': TAG_COLORS.yellow,
	qa: TAG_COLORS.yellow,
	testing: TAG_COLORS.yellow,
	test: TAG_COLORS.yellow,
	validate: TAG_COLORS.yellow,
	verification: TAG_COLORS.yellow,
	staging: TAG_COLORS.yellow,
	check: TAG_COLORS.yellow,
	'follow-up': TAG_COLORS.yellow,
	followup: TAG_COLORS.yellow,
	waiting: TAG_COLORS.yellow,
	blocked: TAG_COLORS.yellow,
	hold: TAG_COLORS.yellow,

	// GREEN — completed / healthy
	done: TAG_COLORS.green,
	complete: TAG_COLORS.green,
	completed: TAG_COLORS.green,
	success: TAG_COLORS.green,
	ok: TAG_COLORS.green,
	stable: TAG_COLORS.green,
	resolved: TAG_COLORS.green,
	fixed: TAG_COLORS.green,
	closed: TAG_COLORS.green,
	merged: TAG_COLORS.green,
	released: TAG_COLORS.green,
	deployed: TAG_COLORS.green,
	approved: TAG_COLORS.green,
	verified: TAG_COLORS.green,
	working: TAG_COLORS.green,
	healthy: TAG_COLORS.green,
	pass: TAG_COLORS.green,
	passing: TAG_COLORS.green,

	// BLUE — information / docs
	info: TAG_COLORS.blue,
	information: TAG_COLORS.blue,
	note: TAG_COLORS.blue,
	docs: TAG_COLORS.blue,
	documentation: TAG_COLORS.blue,
	doc: TAG_COLORS.blue,
	guide: TAG_COLORS.blue,
	help: TAG_COLORS.blue,
	explanation: TAG_COLORS.blue,
	detail: TAG_COLORS.blue,
	details: TAG_COLORS.blue,
	context: TAG_COLORS.blue,
	design: TAG_COLORS.blue,
	discussion: TAG_COLORS.blue,
	proposal: TAG_COLORS.blue,
	idea: TAG_COLORS.blue,

	// MAGENTA — engineering work
	feature: TAG_COLORS.magenta,
	enhancement: TAG_COLORS.magenta,
	improvement: TAG_COLORS.magenta,
	refactor: TAG_COLORS.magenta,
	refactoring: TAG_COLORS.magenta,
	cleanup: TAG_COLORS.magenta,
	optimize: TAG_COLORS.magenta,
	optimization: TAG_COLORS.magenta,
	perf: TAG_COLORS.magenta,
	performance: TAG_COLORS.magenta,
	upgrade: TAG_COLORS.magenta,
	migration: TAG_COLORS.magenta,
	modernize: TAG_COLORS.magenta,
	debt: TAG_COLORS.magenta,

	// CYAN — planning / backlog
	todo: TAG_COLORS.cyan,
	next: TAG_COLORS.cyan,
	planned: TAG_COLORS.cyan,
	plan: TAG_COLORS.cyan,
	future: TAG_COLORS.cyan,
	backlog: TAG_COLORS.cyan,
	investigate: TAG_COLORS.cyan,
	explore: TAG_COLORS.cyan,
	prototype: TAG_COLORS.cyan,
};
