// Builds the epiq-core crate to wasm and embeds it as a base64 string in a
// generated TypeScript module, so esbuild bundles it into the npm package and
// the SEA binaries like any other source — one artifact for every platform,
// nothing written to disk at run time.
//
// Regenerated on every build, never committed: the crate is the source.
import {execFileSync} from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const root = path.resolve(
	path.dirname(fileURLToPath(import.meta.url)),
	'../..',
);
const crate = path.join(root, 'source/rust/epiq-core');
const target = 'wasm32-unknown-unknown';
const wasmFile = path.join(crate, 'target', target, 'release/epiq_core.wasm');
const outFile = path.join(root, 'source/lib/native/epiq-core.wasm.ts');

const INSTALL_HINT = `cargo not found. The Rust core needs a toolchain:

  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

rust-toolchain.toml pins the version and the ${target} target; rustup
installs both on the first build.`;

// PATH first; then the default rustup location, which a shell that has not
// sourced ~/.cargo/env does not have on PATH.
const findCargo = () => {
	const candidates = [
		process.env['CARGO'],
		'cargo',
		path.join(os.homedir(), '.cargo/bin/cargo'),
	].filter(Boolean);

	for (const candidate of candidates) {
		try {
			execFileSync(candidate, ['--version'], {stdio: 'ignore'});
			return candidate;
		} catch {
			// next
		}
	}

	return null;
};

const cargo = findCargo();

if (!cargo) {
	console.error(INSTALL_HINT);
	process.exit(1);
}

execFileSync(cargo, ['build', '--release', '--target', target], {
	cwd: crate,
	stdio: 'inherit',
});

const wasm = fs.readFileSync(wasmFile);

const content = `// Auto-generated by build-rust.mjs from source/rust/epiq-core. Do not edit.
export const EPIQ_CORE_WASM_BASE64 =
\t'${wasm.toString('base64')}';
`;

fs.mkdirSync(path.dirname(outFile), {recursive: true});

// Left alone when unchanged, so a watcher does not see a build as an edit.
if (!fs.existsSync(outFile) || fs.readFileSync(outFile, 'utf8') !== content) {
	fs.writeFileSync(outFile, content);
}

console.log(
	`Wrote epiq-core.wasm.ts from ${(wasm.length / 1024).toFixed(0)} KB of wasm`,
);
