import {CmdKeywords} from '../command-line/command-line-sequence-intent.js';
import {findOverlap} from '../utils/stirng.utils.js';

const COMMON_WORDS = [
	'frontend',
	'backend',
	'exception',
	'incident',
	'defect',
	'regression',
	'degradation',
	'malfunction',
	'refinement',
	'remediation',
	'configuration',
	'optimization',
	'stabilization',
	'enablement',
	'decommission',
	'restructuring',
	'implementation',
	'investigation',
	'validation',
	'verification',
	'dependency',
	'orchestration',
	'provisioning',
	'synchronization',
	'serialization',
	'deserialization',
	'authorization',
	'authentication',
	'observability',
	'compatibility',
	'interoperability',

	'initialization',
	'instantiation',
	'propagation',
	'aggregation',
	'consolidation',
	'normalization',
	'standardization',
	'containerization',
	'virtualization',
	'parallelization',
	'parameterization',
	'reconciliation',
	'transformation',
	'correlation',
	'segmentation',
	'prioritization',
	'categorization',
	'optimization',
	'throttling',
	'rateLimiting',
	'backpressure',
	'deadlocking',
	'contention',
	'fragmentation',
	'saturation',
	'exhaustion',
	'escalation',
	'mitigation',
	'contamination',
	'invalidation',
	'deprecation',
	'obfuscation',
	'compensation',
	'idempotency',
	'consistency',
	'concurrency',
	'parallelism',
	'distribution',
	'partitioning',
	'replication',
	'failover',
	'redundancy',
	'obsolescence',
	'interruption',
	'subscription',
	'notification',
	'calibration',
	'diagnostics',
	'instrumentation',
	'telemetry',
	'aggregation',
	'encapsulation',
	'abstraction',
	'modularization',
	'extensibility',
	'configurability',
	'maintainability',
	'resiliency',
	'recoverability',
	'observability',

	'information',
	'communication',
	'administration',
	'responsibility',
	'opportunity',
	'development',
	'management',
	'performance',
	'production',
	'distribution',
	'maintenance',
	'construction',
	'collaboration',
	'coordination',
	'preparation',
	'participation',
	'implementation',
	'modification',
	'interpretation',
	'presentation',
	'demonstration',
	'comparison',
	'consideration',
	'investigation',
	'understanding',
	'improvement',
	'achievement',
	'experience',
	'environment',
	'technology',
	'infrastructure',
	'architecture',
	'community',
	'population',
	'operation',
	'integration',
	'application',
	'evaluation',
	'conclusion',
	'recommendation',
	'alternative',
	'possibility',
	'capability',
	'flexibility',
	'complexity',
	'priority',
	'security',
	'confidentiality',
	'availability',
	'accessibility',
	'reliability',
	'sustainability',
	'efficiency',
	'effectiveness',
	'consistency',
	'transparency',
	'accountability',
	'compliance',
	'governance',
	'strategy',
	'initiative',
	'commitment',
	'leadership',
	'professional',
	'individual',
	'communication',
	'significance',
	'consequence',
	'circumstance',
	'situation',
	'requirement',
	'condition',
	'functionality',
];

export const getCommandHint = (command: string) => {
	return getHint(Object.values(CmdKeywords), command, 1);
};
export const getWordHint = (command: string) => {
	return getHint([...COMMON_WORDS], command, 3);
};

const getHint = (wordList: string[], command: string, overlapThreshold = 1) => {
	if (!command) return '';

	const words = command.split(' ');
	const lastWord = words.at(-1) || '';
	if (!lastWord) return '';

	const hint = wordList.find(
		term =>
			term.startsWith(lastWord) &&
			findOverlap(lastWord, term) >= overlapThreshold,
	);

	return hint || '';
};
