// Everything the time scrubber computes or remembers, with no JSX. The chart
// parts and the component that arranges them draw against this.

export {
	clamp,
	isLayoutMode,
	TRACK_HEIGHT,
	EVENTS_SCATTER_HEIGHT,
	EVENTS_MODE_VERTICAL_PADDING,
	FLOW_SLOT_PX,
	flowGeometry,
	flowLineY,
	flowStrandCentre,
	TRACK_HIT_PADDING,
	HOVER_HINT_WIDTH,
	SEGMENT_BOUNDARY_COLOR,
	SEGMENT_LABEL_COLOR,
	SEGMENT_HIGHLIGHT_COLOR,
	BUCKET_HIGHLIGHT_COLOR,
	NEEDLE_COLOR,
	NEEDLE_PARKED_COLOR,
	NEEDLE_PARKED_GLOW,
	UNAPPLIED_EDGE_COLOR,
	UNAPPLIED_VEIL_COLOR,
	UNAPPLIED_VEIL_IMAGE,
	SCOPED_OUTLINE_COLOR,
	SCOPED_OUTLINE_INSET_X,
	SCOPED_OUTLINE_INSET_Y,
	RANGE_SELECTION_COLOR,
	RANGE_SELECTION_EDGE,
	NEEDLE_GRIP_WIDTH,
	MIN_RANGE_DRAG_PX,
	MIN_ZOOM_SPAN_MS,
	barWidthCss,
	dotEntranceScale,
	dotExitScale,
	dotAppearAnimation,
	dotExitAnimation,
	DOT_EXIT_TOTAL_MS,
	barGrowAnimation,
	BAR_ENTRANCE_TOTAL_MS,
	FADE_IN_ANIMATION,
	SCRUBBER_KEYFRAMES,
	SCRUBBER_PAGER_STYLES,
	PAGE_ARROW_CLASS,
	PAGED_TRACK_CLASS,
	useNarrowBar,
	usePrefersReducedMotion,
	useExitTransition,
	stackedBarShape,
} from './layout';
export type {FlowGeometry, LayoutMode, SeriesPresence} from './layout';
export {
	bucketCountForSpan,
	buildAxis,
	isScrubbable,
	bucketIssueCounts,
	bucketCommitStats,
	clampingMax,
	populatedRange,
	hourFractionForTime,
} from './axis';
export type {CommitBucketStats, ScrubberAxis, VolumeBar} from './axis';
export type {SegmentBoundary} from './time';
export {
	BOARD_VIEWS,
	isBoardView,
	boardViewColor,
	FILTER_AXES,
	activeAxes,
	narrowedIds,
	plottedView,
	isFilterAxis,
	identityAxisFor,
	categoryOf,
	listIdentities,
	listIdentitiesByAxis,
	soleVisibleIdentity,
	dotDetail,
	isShown,
	keptIssueIds,
	buildEventDots,
	buildBoardFilter,
	windowNamesIssues,
	windowIssueIds,
	actorIdsByIssue,
	issuePassesBoardFilter,
} from './series';
export type {
	EventCategory,
	BoardView,
	EventDot,
	FilterAxis,
	AxisNarrowing,
	SelectionNarrowing,
	BoardFilter,
	IssueFilterFacts,
} from './series';
export {
	chooseGrainUnit,
	chooseSegmentUnit,
	segmentAt,
	segmentBoundaries,
	shortSegmentLabel,
	formatInterval,
	SCOPES,
	isScope,
	isPeriodWindow,
	getPeriodRange,
	formatPeriodLabel,
	scopeButtonLabel,
} from './time';
export {
	createWheelPager,
	isHorizontalWheel,
	WHEEL_PAGE_THRESHOLD_PX,
	WHEEL_GESTURE_QUIET_MS,
} from './paging';
export type {PageDirection, WheelPager} from './paging';
export type {Segment, Scope, PeriodRange} from './time';
export {
	buildFlowChart,
	CLOSED_STRAND_ID,
	flowPathAt,
	flowStrandOf,
	flowVertexAt,
} from './flow';
export type {
	FlowChart,
	FlowLane,
	FlowPath,
	FlowStrand,
	FlowVertex,
} from './flow';
